name: ItemEnchantment
version: 1.0.0
api: 1.10.0
main: LiveWireTech\ItemEnchantment\ItemEnchantment

commands:
 EnchantItem:
  description: "Enchant an item that is defined in the config"
  usage: "/EnchantItem"
  permission: ItemEnchantment.command.Enchant